ansible_host: YOUR_SERVER_IP_ADDRESS
ansible_user: matrix
ansible_ssh_private_key_file: ~/.ssh/matrix
ansible_become_pass: "root_pass"

synapse_postgres_pass: "pg_pass"
synapse_registration_shared_secret: "reg_sh_pass"
synapse_macaroon_secret_key: "macaroon_pass"
synapse_form_secret: "form_pass"


# MATRIX ID SECRETS
matrix_domain: "matrix_domain"
matrix_server_name: "server_name"
element_web_domain: "element_web_domain"

letsencrypt_email: "let's encrypt email'"

# TURN
turn_domain: "turn.domain.name"
turn_static_auth_secret: "stat_auth_pass"
turn_realm: "turn_realm_host"

public_ip: "public ip address"

